spring:
  application:
    name: BOOK-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/booksservice

server:
  port: 8091


#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect